### ISSUE TITLE
rx-bolt driver

### ISSUE THREAD

**Issue by jexp** [LendingClub/neorx#16]
Really nice effort. 

It would be amazing if you'd had the time to look into an reactive driver for the bolt protocol too.

Probably best by wrapping the java driver at an low level and converting the PULL protocol commands to Event Sources.

If you need to we could get you access to the people in the drivers team.

Cheers, Michael

**Comment by if6was9** [comment]
Sure.  As luck will have it, I got bolt support mostly done over the weekend actually. 

I started this project mostly because we were using pre-jdk8 runtime and didn't have streams.  RxJava did. 

So it really isn't very reactive or asynchronous or efficient. ;-). But it has been AWESOME for our needs. 

But yes, an alternate API that is bolt-native, reactive and async might be in the works.

**Comment by if6was9** [comment]
BOLT protocol is now implemented in version 2.x of NeoRx.  

The entire response is processed in memory.  No reactive streaming yet.
